version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./whatsapp-auth:/usr/src/app/whatsapp-auth
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.wwebjs_cache:/usr/src/app/.wwebjs_cache
    environment:
      - NODE_ENV=production
      - TZ=America/Guatemala
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'

volumes:
  whatsapp_auth:
  whatsapp_cache:
  whatsapp_data: