version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - whatsapp_auth:/usr/src/app/.wwebjs_auth
      - whatsapp_cache:/usr/src/app/.wwebjs_cache
      - whatsapp_data:/usr/src/app/whatsapp-auth
    environment:
      - NODE_ENV=production
      - TZ=America/Guatemala

volumes:
  whatsapp_auth:
  whatsapp_cache:
  whatsapp_data: