version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./.wwebjs_auth
        target: /usr/src/app/.wwebjs_auth
      - type: bind
        source: ./.wwebjs_cache
        target: /usr/src/app/.wwebjs_cache
      - type: bind
        source: ./whatsapp-auth
        target: /usr/src/app/whatsapp-auth
    environment:
      - NODE_ENV=production
      - TZ=America/Guatemala

volumes:
  whatsapp_auth:
  whatsapp_cache:
  whatsapp_data: