version: '3'
services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.wwebjs_cache:/usr/src/app/.wwebjs_cache
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"
    user: "1000:1000"